import localFont from "next/font/local";
import { Roboto_Mono } from "next/font/google";

import { AuthProvider } from "@/lib/AuthContext";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import Link from "next/link";

import "./root.css";

const font = Roboto_Mono({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const links = [
        {
            href: "/",
            label: "Home",
        },
        {
            href: "/about",
            label: "About",
        },
        {
            href: "/user/signin",
            label: "Login",
        },
    ];

    return (
        <html lang="en">
            <body className={`${font.className}`}>
                <AuthProvider>
                    <Header />
                    <div className="flex flex-row w-full h-full">
                        <nav className="left-nav">
                            { links.map(({ href, label }, idx) => <Link href={href} key={idx}>{label}</Link> ) }
                        </nav>
                        <div className="container999 flex flex-col">
                            <div className="main-content m-[auto]">{children}</div>
                            <Footer />
                        </div>
                    </div>
                </AuthProvider>
            </body>
        </html>
    );
}
