import localFont from "next/font/local";
import { UnifrakturMaguntia } from "next/font/google";
import "./root.css";

import { AuthProvider } from "@/lib/AuthContext";

import Link from "next/link";

const font = UnifrakturMaguntia({
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <nav className="top-nav"></nav>
        <AuthProvider>
          <div className="main-container">
            <nav className="left-nav">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/contact">Contact</Link>
              <Link href="/(public)/user/signin">Login</Link>
            </nav>
            <main className="main-content">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
