import localFont from "next/font/local";
import { UnifrakturMaguntia } from "next/font/google";
import "./root.css";

import { AuthProvider } from "@/lib/AuthContext";

import Link from "next/link";

const font = UnifrakturMaguntia({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const links = [
        {
            href: "/",
            label: "Home",
        },
        {
            href: "/about",
            label: "About",
        },
        {
            href: "/contact",
            label: "Contact",
        },
        {
            href: "/user/signin",
            label: "Login",
        },
    ];

  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <nav className="top-nav"></nav>
        <AuthProvider>
          <div className="main-container">
            <nav className="left-nav">
              { links.map(({ href, label }, idx) => <Link href={href} key={idx}>{label}</Link> ) }
            </nav>
            <main className="main-content">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
