import localFont from "next/font/local";
import { UnifrakturMaguntia } from "next/font/google"
import "./root.css";

import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import Link from "next/link";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyAj-xUrRB-w6ZW5l_MGyF70z5be1cZxno4",
  authDomain: "pr0j-f8d00.firebaseapp.com",
  projectId: "pr0j-f8d00",
  storageBucket: "pr0j-f8d00.firebasestorage.app",
  messagingSenderId: "1015732342684",
  appId: "1:1015732342684:web:218b07a0a8bcdf1c404259"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);

const font = UnifrakturMaguntia({
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <nav className="top-nav"></nav>
        <div className="main-container">
          <nav className="left-nav">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
          </nav>
          <div className="main-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
